language: node_js
node_js:
- 6
- node
sudo: false
cache:
  directories:
  - node_modules
install:
- npm install eslint -g
- npm install babel-eslint -g
- npm install eslint-config-google -g
script:
- eslint .
